// Mocks generated by Mockito 5.4.4 from annotations
// in application/test/common/common_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:domain/src/internationalization/i18n_repository.dart' as _i2;
import 'package:domain/src/internationalization/language.dart' as _i3;
import 'package:domain/src/internationalization/loc_string.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [I18nRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockI18nRepository extends _i1.Mock implements _i2.I18nRepository {
  MockI18nRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Language get currentLanguage => (super.noSuchMethod(
        Invocation.getter(#currentLanguage),
        returnValue: _i3.Language.english,
      ) as _i3.Language);

  @override
  set currentLanguage(_i3.Language? newCurrentLanguage) => super.noSuchMethod(
        Invocation.setter(
          #currentLanguage,
          newCurrentLanguage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> loadStrings() => (super.noSuchMethod(
        Invocation.method(
          #loadStrings,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  Map<String, _i5.LocString> getAllStrings() => (super.noSuchMethod(
        Invocation.method(
          #getAllStrings,
          [],
        ),
        returnValue: <String, _i5.LocString>{},
      ) as Map<String, _i5.LocString>);
}
