name: loomiarts_site
description: "Loomiarts"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  presentation:
    path: 'modules/presentation'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/squad51/banner.png
    - assets/squad51/banner_en.png
    - assets/squad51/poster.png
    - assets/squad51/poster_en.png
    - assets/loomiarts_logo.png
    - assets/loomiarts_logo_transparent.png
    - assets/texts.json
    - assets/about.json
    - assets/games.json
