name: presentation
description: "Presentation layer module"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.0
  application:
    path: '../application'
  domain:
    path: '../domain'
  infrastructure:
    path: '../infrastructure'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
