// Mocks generated by Mockito 5.4.4 from annotations
// in application/test/game/game_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:application/src/game/game_router.dart' as _i2;
import 'package:domain/domain.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GameRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameRouter extends _i1.Mock implements _i2.GameRouter {
  MockGameRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void navigateBack() => super.noSuchMethod(
        Invocation.method(
          #navigateBack,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void navigateToExternalLink(_i3.ExternalLink? link) => super.noSuchMethod(
        Invocation.method(
          #navigateToExternalLink,
          [link],
        ),
        returnValueForMissingStub: null,
      );
}
